### ISSUE TITLE
Any chance GDAL 3.4.1 could be supported?

### ISSUE THREAD

**Issue by marklit** [MJCruickshank/SARfish#7]
Any chance GDAL 3.4.1 could be supported? It's the latest version the package manager for Ubuntu for Windows supports out of the box.

```bash
$ wget -O test.tif https://umbra-open-data-catalog.s3.amazonaws.com/sar-data/tasks/ad%20hoc/Haneda_Japan/0028c361-193c-49b7-ad59-808033d5dc74/2024-02-27-01-18-51_UMBRA-07/2024-02-27-01-18-51_UMBRA-07_CSI.tif
$ python SARfish.py test.tif detections.geojson 0.5
```

```
Finding ships
  4%|███▊                                                                                           | 16/400 [00:45<18:06,  2.83s/it]
Traceback (most recent call last):
  File "/mnt/d/code_gis/SARfish/SARfish.py", line 363, in <module>
    get_geojson_detections(tiff_filepath, shard_dir, output_geojson_filepath)
  File "/mnt/d/code_gis/SARfish/SARfish.py", line 322, in get_geojson_detections
    detections_lat_lon = pixel_bb_to_coord_bb(coords_list, image_fp)
  File "/mnt/d/code_gis/SARfish/SARfish.py", line 262, in pixel_bb_to_coord_bb
    lat_lon_detection = pixel2coord(image_path, centerx, centery)
  File "/mnt/d/code_gis/SARfish/SARfish.py", line 209, in pixel2coord
    lat_lon = transform.TransformPoint(xp, yp)
  File "/home/mark/.sarfish/lib/python3.10/site-packages/osgeo/osr.py", line 1150, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'CoordinateTransformation_TransformPoint'.
  Possible C/C++ prototypes are:
    OSRCoordinateTransformationShadow::TransformPoint(double [3])
    OSRCoordinateTransformationShadow::TransformPoint(double [4])
    OSRCoordinateTransformationShadow::TransformPoint(double [3],double,double,double)
    OSRCoordinateTransformationShadow::TransformPoint(double [4],double,double,double,double)
```

```bash
$ pip freeze
```

```
affine==2.4.0
asttokens==2.4.1
attrs==23.2.0
certifi==2024.6.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
contourpy==1.2.1
cycler==0.12.1
decorator==5.1.1
exceptiongroup==1.2.1
executing==2.0.1
filelock==3.15.4
fonttools==4.53.0
fsspec==2024.6.1
GDAL==3.4.1
geopandas==1.0.0
ipython==8.25.0
jedi==0.19.1
Jinja2==3.1.4
kiwisolver==1.4.5
MarkupSafe==2.1.5
matplotlib==3.9.0
matplotlib-inline==0.1.7
mpmath==1.3.0
networkx==3.3
numpy==2.0.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.5.40
nvidia-nvtx-cu12==12.1.105
packaging==24.1
pandas==2.2.2
parso==0.8.4
pexpect==4.9.0
pillow==10.3.0
prompt_toolkit==3.0.47
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.18.0
pyogrio==0.9.0
pyparsing==3.1.2
pyproj==3.6.1
python-dateutil==2.9.0.post0
pytz==2024.1
rasterio==1.3.10
shapely==2.0.4
six==1.16.0
snuggs==1.4.7
stack-data==0.6.3
sympy==1.12.1
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.4
traitlets==5.14.3
triton==2.3.1
typing_extensions==4.12.2
tzdata==2024.1
wcwidth==0.2.13
```

**Comment by marklit** [comment]
I found casting the numpy.float32s to floats fixed the issue.

```diff
-    lat_lon = transform.TransformPoint(xp, yp)
+    lat_lon = transform.TransformPoint(float(xp), float(yp))
```
